import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTrigger,
} from "@/components/ui/sheet"
import Logo from '../../public/sklogo.png'
import { Menu } from 'lucide-react'
import Footer from '../app/portions/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SK Dev Portfolio',
  description: 'Generated by Sameed Saeed Khan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-gray-700 to-black`}>
          <header className='flex justify-between px-20 items-center '>

            <div>
              <img src= {Logo.src} className='w-20'/>
            </div>

            <div className='md:hidden'>
              <Sheet>
                <SheetTrigger>
                  <Menu className='text-[#86c9eb]'/>
                </SheetTrigger>
                <SheetContent className=' backdrop-blur-lg bg-gradient-to-r from-gray-700 to-black'>
                  <SheetHeader>
                    <img src= {Logo.src} className='w-20'/>
                  </SheetHeader>
                  <ul className='text-lg text-[#86c9eb] font-bold'>
                      <li>
                        <Link href={"/"} className='hover:text-transparent bg-clip-text bg-gradient-to-r from-blue-200 to-blue-400 transition duration-6000'>Home</Link>
                      </li>
                      <li>
                        <Link href= "/about" className='hover:text-transparent bg-clip-text bg-gradient-to-r from-blue-200 to-blue-400 transition duration-6000'>About</Link>
                      </li>
                      <li>
                        <Link href= "/skills" className='hover:text-transparent bg-clip-text bg-gradient-to-r from-blue-200 to-blue-400 transition duration-6000'>Skills</Link>
                      </li>
                      <li>
                        <Link href= "/works" className='hover:text-transparent bg-clip-text bg-gradient-to-r from-blue-200 to-blue-400 transition duration-6000'>My Works</Link>
                      </li>
                    </ul>
                </SheetContent>
              </Sheet>
            </div>

            <div className='hidden md:flex'>
              <ul className='flex justify-evenly gap-x-6 text-lg text-[#86c9eb] font-extrabold '>
                <li>
                  <Link href={"/"} className='hover:text-transparent bg-clip-text bg-gradient-to-r from-blue-200 to-blue-400 transition duration-6000'>Home</Link>
                </li>
                <li>
                  <Link href= "/about" className='hover:text-transparent bg-clip-text bg-gradient-to-r from-blue-200 to-blue-400 transition duration-6000'>About</Link>
                </li>
                <li>
                  <Link href= "/skills" className='hover:text-transparent bg-clip-text bg-gradient-to-r from-blue-200 to-blue-400 transition duration-6000'>Skills</Link>
                </li>
                <li>
                  <Link href= "/works" className='hover:text-transparent bg-clip-text bg-gradient-to-r from-blue-200 to-blue-400 transition duration-6000'>My Works</Link>
                </li>
              </ul>
            </div>

          </header>

          {children}
        <Footer/>
      </body>
    </html>
  )
}
